"""Shared imports and test fixtures used by every split test module.

Generated by _split_test_runner.py from the original
tests/test_cubie_derby.py prelude. All names defined here are
re-exported via `from tests._shared import *` so that the per-domain
test files need no extra setup.
"""
from __future__ import annotations

import contextlib
import io
import json
import random
import re
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch

from cubie_derby_core.champion_interactive import (
    InteractiveWizardUI,
    _emit_runner_progress,
    _prompt_line,
    _prompt_yes_no,
    _runner_catalog_lines,
)
from cubie_derby_core.interactive_i18n import translate_interactive_text
from cubie_derby_core.tournament_context import (
    tournament_entry_request_from_dict,
    tournament_entry_request_to_dict,
)

from cubie_derby import (
    MonteCarloAccumulator,
    ProgressBar,
    RaceSkillState,
    RaceConfig,
    RaceMovementState,
    TraceLogger,
    apply_lynae_skill,
    apply_sigrika_debuff,
    build_config_from_args,
    check_chisa_skill,
    check_denia_skill,
    check_hiyuki_bonus,
    current_rank,
    display_position,
    display_width,
    format_summary,
    format_season_roster_scan_summary,
    format_tournament_result,
    format_simulation_overview_lines,
    champion_prediction_to_dict,
    champion_parallel_task_count,
    champion_progress_batch_size,
    format_champion_prediction_summary,
    summary_to_dict,
    main,
    make_start_grid,
    mark_sigrika_debuffs,
    maybe_trigger_aemeath_after_active_move,
    maybe_trigger_luno_after_action,
    maybe_trigger_player1_skill_after_action,
    initial_player_order,
    next_round_action_order,
    move_npc,
    move_group_due_to_cell_effect,
    move_runner_with_left_side,
    move_single_runner,
    normalize_cli_args,
    parallel_task_count,
    progress_batch_size,
    parse_runner,
    parse_runner_tokens,
    parse_start_layout,
    parse_start_spec,
    rank_scope,
    run_skill_ablation,
    run_monte_carlo,
    run_champion_prediction_monte_carlo,
    run_champion_prediction_from_entry_request_monte_carlo,
    run_season_roster_scan,
    simulate_stage,
    simulate_tournament_from_entry_request,
    simulate_tournament,
    TournamentEntryRequest,
    get_tournament_entry_point_definition,
    TournamentStartRequest,
    build_tournament_entry_request,
    build_tournament_plan,
    tournament_entry_point_choices,
    tournament_entry_requirements,
    get_tournament_phase_definition,
    season_rules,
    season_roster_combination_count,
    season_roster_scan_to_dict,
    season_runner_pool,
    settle_npc_end_of_round,
    simulate_race,
    skill_ablation_to_dict,
    split_iterations,
    tournament_phase_choices,
    roll_dice,
    roll_round_dice,
    with_elapsed,
)


def argparse_namespace(**kwargs):
    defaults = {
        "season": 1,
        "match_type": None,
        "champion_prediction": None,
        "champion_analysis": "fast",
        "runners": None,
        "track_length": None,
        "start": None,
        "initial_order": None,
        "seed": None,
        "iterations": 100,
        "field_size": None,
        "workers": 1,
        "json": False,
        "trace": False,
        "trace_log": None,
        "season_roster_scan": False,
        "skill_ablation": False,
        "skill_ablation_runners": None,
        "skill_ablation_detail": False,
        "tournament_context_in": None,
        "tournament_context_out": None,
        "qualify_cutoff": 4,
    }
    defaults.update(kwargs)
    return type("Args", (), defaults)()


class CountingRandom(random.Random):
    def __init__(self, random_value: float = 0.1):
        super().__init__(1)
        self.random_value = random_value
        self.random_calls = 0

    def random(self) -> float:
        self.random_calls += 1
        return self.random_value


class FixedDiceRandom(CountingRandom):
    def __init__(self, random_value: float, dice_value: int):
        super().__init__(random_value)
        self.dice_value = dice_value

    def randint(self, a: int, b: int) -> int:
        if not a <= self.dice_value <= b:
            raise ValueError(f"fixed dice {self.dice_value} is outside {a}..{b}")
        return self.dice_value


class FixedDiceShuffleRandom(FixedDiceRandom):
    def shuffle(self, x) -> None:
        x.reverse()


class QueuedFloatDiceShuffleRandom(random.Random):
    def __init__(self, random_values: list[float], dice_value: int, fallback_random: float = 0.9):
        super().__init__(1)
        self.random_values = list(random_values)
        self.dice_value = dice_value
        self.fallback_random = fallback_random

    def random(self) -> float:
        if not self.random_values:
            return self.fallback_random
        return self.random_values.pop(0)

    def randint(self, a: int, b: int) -> int:
        if not a <= self.dice_value <= b:
            raise ValueError(f"fixed dice {self.dice_value} is outside {a}..{b}")
        return self.dice_value

    def shuffle(self, x) -> None:
        x.reverse()


class QueuedRandom(CountingRandom):
    def __init__(self, randint_values: list[int], random_value: float = 0.9):
        super().__init__(random_value)
        self.randint_values = list(randint_values)

    def randint(self, a: int, b: int) -> int:
        if not self.randint_values:
            raise AssertionError("no queued randint value left")
        value = self.randint_values.pop(0)
        if not a <= value <= b:
            raise ValueError(f"queued dice {value} is outside {a}..{b}")
        return value


class RecordingShuffleRandom(random.Random):
    def __init__(self):
        super().__init__(1)
        self.shuffle_inputs: list[list[int]] = []

    def shuffle(self, x) -> None:
        self.shuffle_inputs.append(list(x))
        x.reverse()


def first_trace_action(text: str, runner_name: str) -> str:
    start = text.index(f"--- {runner_name}行动 ---")
    next_start = text.find("\n--- ", start + 1)
    if next_start == -1:
        return text[start:]
    return text[start:next_start]


# Explicit re-export list. `from tests._shared import *` honours __all__,
# which lets us include underscore-prefixed names (private internals of
# cubie_derby_core.champion_interactive) that the tests need to reach.
__all__ = [
    # stdlib re-exports
    "contextlib",
    "io",
    "json",
    "random",
    "re",
    "tempfile",
    "unittest",
    "Path",
    "patch",
    # interactive wizard internals
    "InteractiveWizardUI",
    "_emit_runner_progress",
    "_prompt_line",
    "_prompt_yes_no",
    "_runner_catalog_lines",
    "translate_interactive_text",
    "tournament_entry_request_from_dict",
    "tournament_entry_request_to_dict",
    # simulator public API (re-exported through the cubie_derby facade)
    "MonteCarloAccumulator",
    "ProgressBar",
    "RaceSkillState",
    "RaceConfig",
    "RaceMovementState",
    "TraceLogger",
    "apply_lynae_skill",
    "apply_sigrika_debuff",
    "build_config_from_args",
    "check_chisa_skill",
    "check_denia_skill",
    "check_hiyuki_bonus",
    "current_rank",
    "display_position",
    "display_width",
    "format_summary",
    "format_season_roster_scan_summary",
    "format_tournament_result",
    "format_simulation_overview_lines",
    "champion_prediction_to_dict",
    "champion_parallel_task_count",
    "champion_progress_batch_size",
    "format_champion_prediction_summary",
    "summary_to_dict",
    "main",
    "make_start_grid",
    "mark_sigrika_debuffs",
    "maybe_trigger_aemeath_after_active_move",
    "maybe_trigger_luno_after_action",
    "maybe_trigger_player1_skill_after_action",
    "initial_player_order",
    "next_round_action_order",
    "move_npc",
    "move_group_due_to_cell_effect",
    "move_runner_with_left_side",
    "move_single_runner",
    "normalize_cli_args",
    "parallel_task_count",
    "progress_batch_size",
    "parse_runner",
    "parse_runner_tokens",
    "parse_start_layout",
    "parse_start_spec",
    "rank_scope",
    "run_skill_ablation",
    "run_monte_carlo",
    "run_champion_prediction_monte_carlo",
    "run_champion_prediction_from_entry_request_monte_carlo",
    "run_season_roster_scan",
    "simulate_stage",
    "simulate_tournament_from_entry_request",
    "simulate_tournament",
    "TournamentEntryRequest",
    "get_tournament_entry_point_definition",
    "TournamentStartRequest",
    "build_tournament_entry_request",
    "build_tournament_plan",
    "tournament_entry_point_choices",
    "tournament_entry_requirements",
    "get_tournament_phase_definition",
    "season_rules",
    "season_roster_combination_count",
    "season_roster_scan_to_dict",
    "season_runner_pool",
    "settle_npc_end_of_round",
    "simulate_race",
    "skill_ablation_to_dict",
    "split_iterations",
    "tournament_phase_choices",
    "roll_dice",
    "roll_round_dice",
    "with_elapsed",
    # test fixtures
    "argparse_namespace",
    "CountingRandom",
    "FixedDiceRandom",
    "FixedDiceShuffleRandom",
    "QueuedFloatDiceShuffleRandom",
    "QueuedRandom",
    "RecordingShuffleRandom",
    "first_trace_action",
]
